# 基础配置模块 - 常规设置
# 端口和基础配置
port: 7890
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
unified-delay: true
global-client-fingerprint: chrome
secret: 62132

# 锚点定义
rules-domain: &rules-domain 
  type: http
  interval: 86400
  behavior: domain

rules-ip: &rules-ip 
  type: http
  interval: 86400
  behavior: ipcidr

rules-classical: &rules-classical 
  type: http
  interval: 86400
  behavior: classical

# 代理组基础配置锚点
p-groups-base: &p-groups-base
  interval: 86400
  timeout: 3000
  url: "https://www.gstatic.com/generate_204"
  lazy: true
  max-failed-times: 3

# DNS配置模块 - 白名单模式
dns:
  enable: true
  ipv6: false
  respect-rules: true
  enhanced-mode: 
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
    - "+.market.xiaomi.com"
  nameserver:
    - https://120.53.53.53/dns-query
    - https://223.5.5.5/dns-query
  proxy-server-nameserver:
    - https://120.53.53.53/dns-query
    - https://223.5.5.5/dns-query
  nameserver-policy:
    "geosite:cn,private":
      - https://120.53.53.53/dns-query
      - https://223.5.5.5/dns-query
    "geosite:geolocation-!cn":
      - "https://dns.cloudflare.com/dns-query"
      - "https://dns.google/dns-query"

# 代理组配置 - 定义策略组结构，substore 会填充节点引用
proxy-groups:
  # 功能分组
  - name: 节点选择
    <<: *p-groups-base
    type: select
    proxies:
      - 日常使用
      - 我的节点
      - 日本精选
      - 香港精选
      - 美国精选
      - 台湾精选
      - 新加坡精选
      - 其他精选
      - DIRECT
    icon: "https://fyzfly.oss-cn-beijing.aliyuncs.com/img/202409161533607.svg"

  - name: 我的节点
    <<: *p-groups-base
    type: select
    # substore 脚本会通过 use 或 include-all + filter 填充节点
    proxies: []

  - name: AI专用
    <<: *p-groups-base
    type: select
    proxies:
      - webshare
      - 我的节点
      - 节点选择
      - 精选节点

  - name: 日常使用
    <<: *p-groups-base
    type: url-test
    # substore 脚本会填充日常使用的节点
    proxies: []
    icon: "https://fyzfly.oss-cn-beijing.aliyuncs.com/img/202409161436790.svg"

  - name: 精选节点
    type: select
    <<: *p-groups-base
    proxies:
      - 美国精选
      - 日本精选
      - 新加坡精选
      - 台湾精选
      - 香港精选
      - 其他精选
      - 节点选择

  - name: 日本精选
    <<: *p-groups-base
    type: select
    # substore 脚本会通过 filter 填充日本节点
    proxies: []

  - name: 美国精选
    <<: *p-groups-base
    type: select
    # substore 脚本会通过 filter 填充美国节点
    proxies: []

  - name: 香港精选
    <<: *p-groups-base
    type: select
    # substore 脚本会通过 filter 填充香港节点
    proxies: []

  - name: 新加坡精选
    <<: *p-groups-base
    type: select
    # substore 脚本会通过 filter 填充新加坡节点
    proxies: []

  - name: 台湾精选
    <<: *p-groups-base
    type: select
    # substore 脚本会通过 filter 填充台湾节点
    proxies: []

  - name: 其他精选
    <<: *p-groups-base
    type: select
    # substore 脚本会通过 filter 填充其他地区节点
    proxies: []

  - name: 拦截广告
    type: select
    proxies:
      - "REJECT"
      - "DIRECT"
    icon: "https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/block.svg"

  - name: 漏网之鱼
    type: select
    proxies:
      - DIRECT
      - 节点选择
    icon: "https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/fish.svg"

# 规则配置模块 - 包含规则集和路由规则
# 注意：此模块提供基础的规则集和规则配置
# substore 脚本可能会覆盖或补充这些配置
rule-providers:
  # 个人专用
  ryrules:
    <<: *rules-classical
    url: "https://gist.githubusercontent.com/Crush-RY/bfeb6c0e292f0ba3d9c60bbb22f32315/raw/ryrule.yaml"
    path: ./ruleset/ryrules.yaml

  # AI 类
  OpenAI:
    <<: *rules-classical
    path: ./rules/blackmatrix7/OpenAI.yaml
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OpenAI/OpenAI.yaml"

  Gemini:
    <<: *rules-classical
    path: ./rules/blackmatrix7/Gemini.yaml
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Gemini/Gemini.yaml"

  Anthropic:
    <<: *rules-classical
    path: ./rules/blackmatrix7/Claude.yaml
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Anthropic/Anthropic.yaml"

  Copilot:
    <<: *rules-classical
    path: ./rules/blackmatrix7/Copilot.yaml
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Copilot/Copilot.yaml"

  # 广告类
  Advertising:
    <<: *rules-classical
    path: ./rules/blackmatrix7/Advertising_Classical.yaml
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Classical.yaml"

  # 需要代理
  gfw:
    <<: *rules-domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/Loyalsoldier/gfw.yaml

  proxy:
    <<: *rules-domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/Loyalsoldier/proxy.yaml

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/Loyalsoldier/tld-not-cn.yaml

  ProxyClient:
    <<: *rules-classical
    path: ./rules/zuluion/ProxyClient.yaml
    url: "https://cdn.jsdelivr.net/gh/zuluion/Clash-Template-Config@master/Filter/ProxyClient.yaml"

  # 无需代理
  ChinaDomain:
    <<: *rules-domain
    path: ./rules/ACL4SSR/ChinaDomain.yaml
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list"

  ChinaCompanyIp:
    <<: *rules-ip
    path: ./rules/ACL4SSR/ChinaCompanyIp.yaml
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list"

  cncidr:
    <<: *rules-ip
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/Loyalsoldier/cncidr.yaml

  lancidr:
    <<: *rules-ip
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/Loyalsoldier/lancidr.yaml

  # 服务类
  Talkatone:
    <<: *rules-classical
    url: "https://raw.githubusercontent.com/mottzz87/crules/refs/heads/main/rule/talkatone.list"
    path: ./ruleset/mottzz87/talkatone.list

  Telegram:
    <<: *rules-classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Telegram/Telegram.yaml"
    path: ./ruleset/blackmatrix7/Telegram.yaml

  TikTok:
    <<: *rules-classical
    path: ./rules/blackmatrix7/TikTok.yaml
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/TikTok/TikTok.yaml"

  Discord:
    <<: *rules-classical
    path: ./rules/blackmatrix7/discord.yaml
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Discord/Discord.yaml"

  applications:
    <<: *rules-classical
    path: ./rules/Loyalsoldier/applications.yaml
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"

  # 游戏类
  Steam:
    type: http
    behavior: classical
    format: yaml
    path: ./rules/Steam.yaml
    url: "https://cdn.jsdelivr.net/gh/zuluion/Clash-Template-Config@master/Filter/Steam.yaml"
    interval: 86400

# 路由规则配置
# 请设置域名类规则优先，ip类规则置后！
rules:
  - PROCESS-NAME,com.talkatone.android,AI专用
  - PROCESS-NAME,claude.exe,AI专用
  - PROCESS-NAME,claude,AI专用
  - RULE-SET,ryrules,DIRECT
  - DOMAIN-SUFFIX,lunary.site,DIRECT
  - DOMAIN-SUFFIX,genspark.ai,AI专用
  - DOMAIN-SUFFIX,poe.com,AI专用
  - DOMAIN-SUFFIX,you.com,AI专用
  - DOMAIN-SUFFIX,aistudio.google.com,精选节点
  - DOMAIN-SUFFIX,perplexity.ai,AI专用
  - DOMAIN-SUFFIX,linux.do,DIRECT
  - RULE-SET,OpenAI,AI专用
  - RULE-SET,Gemini,精选节点
  - RULE-SET,Anthropic,AI专用
  - RULE-SET,Copilot,我的节点
  - RULE-SET,gfw,节点选择
  - RULE-SET,proxy,节点选择
  - RULE-SET,tld-not-cn,节点选择
  - RULE-SET,ProxyClient,节点选择,no-resolve
  - RULE-SET,Telegram,节点选择
  - RULE-SET,Steam,节点选择
  - RULE-SET,ChinaDomain,DIRECT
  - RULE-SET,ChinaCompanyIp,DIRECT,no-resolve
  - RULE-SET,cncidr,DIRECT,no-resolve
  - RULE-SET,lancidr,DIRECT,no-resolve
  - RULE-SET,applications,DIRECT
  - RULE-SET,Advertising,拦截广告
  - GEOSITE,cn,DIRECT
  - MATCH, 漏网之鱼